# Site settings
title: Glassbox Salon
description: "We invite you to come enjoy and experience a comfortable stress free environment with our team. Our Talented professionals are dedicated to providing outstanding customer service in a relaxing, modern atmosphere. We cater to all salon and spa services and strive to ensure that when our clients leave, they are looking forward to seeing us again. Here at Glassbox Salon we thrive on hospitality and make you our priority. We are committed to giving back to our community by providing products that are sustainable to us and the earth. We look forward to meeting you."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: DentistSmile
    hero_description: A responsive Jekyll theme for dental clinics.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 932 50 540
    emergency: 931 53 234
    email: contact@yoursite.com
    address: Von schroeders 273, <br> Viña del mar - Chile

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2015 DentistSmile - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
